# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-04 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TacosModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombretaqueria', models.CharField(max_length=50)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('calificacion', models.CharField(blank=True, choices=[('EX', '5'), ('BU', '4'), ('RE', '3'), ('MA', '2'), ('MM', '1')], max_length=50, null=True)),
                ('imagen', models.URLField(max_length=50)),
            ],
        ),
    ]
